spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FlywayTestDB?serverTimezone=UTC
    username: root
    password: 123
  flyway:
    locations: "classpath:db/migration"

flyway:
  validate-on-migrate: false
  encoding: UTF8MB4
  out-of-order: true